# Linear Models

In [7]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

from pprint import pprint as print

plt.rcParams['figure.figsize'] = [20.0, 10.0]

## Target Function

In [13]:
N = 5
np.random.seed(0)

x = np.linspace(-N/10, N/10, N)
y = 1.0 + x

## Raw Data

In [16]:
y_ = y + np.random.normal(0,0.5, N)

list(zip(x, y))

[(-0.5, 0.5), (-0.25, 0.75), (0.0, 1.0), (0.25, 1.25), (0.5, 1.5)]

## Preprocessing

In [17]:
X = np.ones((N, 2))
X[:, 1 ] = x

list(zip(X, y))

[(array([ 1. , -0.5]), 0.5),
 (array([ 1.  , -0.25]), 0.75),
 (array([ 1.,  0.]), 1.0),
 (array([ 1.  ,  0.25]), 1.25),
 (array([ 1. ,  0.5]), 1.5)]

## Stochastic Gradient Descent

## Maximum Likelihood Estimator

In [ ]:
H = np.dot(np.dot(X, np.linalg.inv(np.dot(X.T, X))), X.T)
y_hat = np.dot(H, y_)

plt.plot(x, y_, 'o', label='measurements')
plt.plot(x, y, label='target function')
plt.plot(x, y_hat, label='model')
plt.legend();